server:
    port: 8080

spring:
    profiles:
        active: dev
    data:
        mongodb:
            host: ds033831.mongolab.com
            port: 33831
            database: ruta50
            username: ruta50
            password: ruta50
    

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: ruta50


